version: '2'

services:
   plexserver:
       container_name: plex
       image: linuxserver/plex
       restart: always 
       volumes:
           - /mnt/data1/multimedia/animes:/animes
           - /mnt/data1/multimedia/movies:/movies
           - /mnt/data1/multimedia/series:/series
           - /mnt/data1/multimedia/audio/audiobooks:/audiobooks
       network_mode: host
       environment:
           - TZ="Europe/Paris"   
           - PLEX_UID=1000
           - PLEX_GID=1000

   transmission:
       container_name: transmission
       image: linuxserver/transmission
       restart: always 
       volumes:
          - /mnt/data1/downloads:/downloads
          - /mnt/data1/multimedia/movies:/movies
          - /mnt/data1/multimedia/audio/audiobooks:/audiobooks
          - /mnt/data1/opt/transmission/:/config
       ports:
          - 4990:9091
       environment:
           - PUID=1000
           - PGID=1000

   jackett:
       image: linuxserver/jackett
       container_name: jackett
       restart: always
       volumes:
          - /mnt/data1/opt/jackett:/config
          - /etc/localtime:/etc/localtime:ro
       ports:
          - 4991:9117
       environment:
           - TZ="Europe/Paris"   
           - PUID=1000
           - PGID=1000

   sickrage:
       container_name: sickrage
       image: linuxserver/sickchill
       restart: always 
       links:
           - transmission
           - jackett
       volumes:
           - /mnt/data1/opt/sickrage:/config
           - /mnt/data1/downloads/complete:/downloads
           - /mnt/data1/multimedia/animes:/animes
           - /mnt/data1/multimedia/series:/series
           - /etc/localtime:/etc/localtime:ro
       ports:
           - 4992:8081
       environment:
           - TZ="Europe/Paris"   
           - PUID=1000
           - PGID=1000

   joal:
       container_name: joal
       image: anthonyraymond/joal:2.1.19-arm
       restart: always
       volumes:
          - /mnt/data1/opt/joal:/data1
       ports:
          - 4993:4993
       environment:
           - _JAVA_OPTIONS='-Djava.net.preferIPv6Addresses=true'
       command: --joal-conf="/data1" --spring.main.web-environment=true --server.port="4993" --joal.ui.path.prefix="joal"  --joal.ui.secret-token="phenixzr"

   samba:
       container_name: samba
       image: elswork/samba
       restart: always 
       network_mode: host
       volumes:
           - /mnt/data1/opt/joal/torrents/:/mount/joal
           - /mnt/data1/downloads/:/mount/downloads
           - /mnt/data1/multimedia/:/mount/multimedia
           - /mnt/data1/:/mount/Share
       ports:
           - 137:137/udp
           - 138:138/udp
           - 139:139
           - 445:445
           - 445:445/udp
       environment:
           - USERID=1000
           - GROUPID=1000
       command: -u "olivier:2207" -s "downloads:/mount/downloads:rw:olivier" -s "joal:/mount/joal:rw:olivier" -s "multimedia:/mount/multimedia:rw:olivier" -s "Share:/mount/Share:rw:olivier"
       
